[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "0.0.0"
version_scheme = "semver"
version = "0.0.1"
update_changelog_on_bump = true

[changelog.ignore]
types = ["chore", "docs", "test"]
scopes = ["ci", "deps"]

